version: "3.8"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`www.wele.fr`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$RHNoxtd9$$Y8RoCSL10ymRaYeEe4mJL/"
      - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://(?:www\\.)?(.+)"
      - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://www.$${1}"
      #- "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://www\\.(.+)"
      #- "traefik.http.middlewares.strip-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.strip-www.redirectregex.permanent=true"
    networks:
      - web

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wele_literie
    ports:
      - "3308:3306"
    networks:
        - web
    volumes:
        - ./db-data-wele:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    #environment:
      # PMA_HOST: db
      # PMA_USER: root
      # PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
        - web
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_wele
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
    restart: always
    networks:
        - web  
  www:
    build: "php.apache"
    # env_file: project/.env
    container_name: www_docker_wele
    #ports:
    #  - "80:80"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.www_docker_wele.rule=Host(`wele.fr`)"
      - "traefik.http.routers.www_docker_wele.entrypoints=websecure"
      - "traefik.http.routers.blog.rule=Host(`www.wele.fr`, `wele.fr`)"
      - "traefik.http.routers.blog.middlewares=strip-www"
    volumes:
        #- ./8.0/php.ini:/usr/local/etc/php/php.ini
        - ./php.apache/conf:/etc/apache2/sites-enabled
        - ./project:/var/www
    restart: always
    networks:
        - web
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "0"
      APP_SECRET: "EDITME"
      DATABASE_URL: mysql://root:root@db/wele_literie


networks:
  web:
    external: false


#volumes:
  #db-data-wele:  

